### ISSUE TITLE
Add german Umlauts to QWERTZ

### ISSUE THREAD

**Issue by KloolK** [Julow/Unexpected-Keyboard#50]
As discussed in #20, the german Umlauts ä, Ä, ö, Ö, ü, Ü should be added to the a, o and u keys directly without having to pick the ◌̈ first.

I could help contributing the Umlauts back. However, I'm not sure whether its worth setting up the dev environment, since the commits in #20 seem to contain everything we need already.
What do you think?

**Comment by Julow** [comment]
Works for me :) I would like to ear your others opinions on the layout as it is now (other than the Umlauts).
The next release is planned for at least in two weeks.

**Comment by Julow** [comment]
Fixed (b1ef21f). At the same time I removed the dead keys from the keyboard, does that work for you ? The `?` is also moved because it was too close to the edge of the screen.

**Comment by KloolK** [comment]
Thank you, looking great :tada:

**Comment by FadeFx** [comment]
hey, jus% instaled v1.13.0 from fdroid, but umlaut keys are still missing...

**Comment by Julow** [comment]
The umlauts are on the QWERTZ layout (if you have the German language installed on your decide and don't choose a different in the settings). The QWERTY layout only has dead-keys.

**Comment by Julow** [comment]
If you need QWERTY with dedicated keys for the umlauts, you'll need to add a new layout for that as it is done for Latvian and Spanish for example.
