### ISSUE TITLE
If the language is not supported, Unexpected Keyboard falls back to Arabic layout instead of QWERTY (US) layout

### ISSUE THREAD

**Issue by antermin** [Julow/Unexpected-Keyboard#700]
**Describe the bug**
If Android is set to a language which is not supported by Unexpected Keyboard, it falls back to Arabic layout instead of QWERTY (US) layout.

**To Reproduce**
1. In Unexpected Keyboard's settings, check that "Layout 1" is set to "System settings".
2. In Android's settings, set the language to an unsupported one, for example Japanese.

**Comment by Julow** [comment]
Thanks for reporting, should be fixed by 4629410

**Comment by ClassicOldSong** [comment]
This issue still exists in version 1.29.1, the keyboard layout is detected as Arabic by the system.

**Comment by Julow** [comment]
@ClassicOldSong Fixed in 91751af
