### ISSUE TITLE
Unwanted additional padding below keyboard

### ISSUE THREAD

**Issue by ShroudedNight** [Julow/Unexpected-Keyboard#854]
Hello,

Galaxy S23
SM-S911W
Android 14
Unexpected Keyboard v1.30.1

The latest version from Google Play seems to be offset significantly from the button bar:

![Screenshot_20241227_141105_Firefox Beta](https://github.com/user-attachments/assets/8b075b13-78f9-4e9e-a9b3-c045537c877d)

**Comment by syskill** [comment]
Same on OnePlus 6T running LineageOS 21-20241210-NIGHTLY-fajita.

**Comment by twoquestions** [comment]
I also have this issue, on a Samsung Fold 5, in both portrait and landscape modes.

**Comment by Julow** [comment]
This is related to https://github.com/Julow/Unexpected-Keyboard/issues/842 and should be fixed. Here's a debug version of the app if you want to try it: https://github.com/Julow/Unexpected-Keyboard/actions/runs/12507485318

**Comment by Spike-from-NH** [comment]
Saw it too, on a BLU 5 running Android 14. Fixed in v1.30.2, thanks!

**Comment by Julow** [comment]
Thanks for confirming!

**Comment by adrian4096** [comment]
Same problem persists in v 1.30.3 (from f-droid). Ty in advance
![Screenshot_20250104-010359_Unexpected Keyboard](https://github.com/user-attachments/assets/fae2fe40-f613-4c53-b279-fce1a9a50500)

**Comment by Spike-from-NH** [comment]
But has not returned on my BLU 5.
