### ISSUE TITLE
Blank space below the keyboard

### ISSUE THREAD

**Issue by user889252627** [Julow/Unexpected-Keyboard#875]
Hi!
Recently Android 15 came out for my phone and after upgrading to it I noticed that the keyboard got offset upwards. I tried reinstalling the app and restarting my phone. I also tried using other custom mappings and default ones but nothing helped. What could be the issue? Thanks for the help in advance!![Screenshot_20250110-151715.Moto App Launcher.png](https://github.com/user-attachments/assets/23ab0844-5045-4e0a-8178-df1f246d41ca)

![Screenshot_20250110-151652.Moto App Launcher.png](https://github.com/user-attachments/assets/3d7c3674-8cb8-4eea-a19c-d5656e0a7aa3)

**Comment by Spike-from-NH** [comment]
Please install v1.30.3 of the keyboard. This bug appeared around v1.30.0 but was promptly fixed.

**Comment by user889252627** [comment]
I checked it's version which turned out to be 1.30.3 so I reinstalled it from the 1.30.3 apk (since I downloaded it from google play originally) but it didn't help either.

**Comment by user889252627** [comment]
Installing a previous version (1.30.0) actually solved the issue. Thanks for the help!

**Comment by Spike-from-NH** [comment]
So what you did was back up before the bug appeared. It was reported by #842 and fixed in v1.30.2, but that version crashed a lot and 1.30.3 fixed that.

If the bug is still present in 1.30.3, you should give @Julow more detailed information so he can fix it for good.

If you're getting APKs from here and the Play Store, I wonder if there's a version discrepancy—also if you had two keyboards installed at the same time, making it unclear which was exhibiting the bug.

**Comment by user889252627** [comment]
I don't think there is any sort of mismatch between the playstore and the github variant from what I figured out via testing.
About providing more details to fix this bug, since it's still present: android 15, Motorolla phone (I can provide more if necessary), anything above and including 1.30.0 had  the issue.
1.30.0 only had the issue when the gesture navigation bar was disabled (as seen on my first screenshots, I was using my phone like that before) and enabling the bar removed the gap below the keyboard and also the little bar with an icon to switch and one to change the keyboard (as seen on the inckuded image)![Screenshot_20250116-000919.Moto App Launcher.png](https://github.com/user-attachments/assets/75ac6e62-dd6b-4c77-94f1-40b998f7e870)

At the time of testing I only had the Unexpected keyboard enabled.
I think I'll just stick with 1.30.0 with the bar enabled since any gap below is just unnecessary imo.
I hope I was able to help!

**Comment by Julow** [comment]
Thanks for opening an issue with screenshots :)
I fail to reproduce the issue in my emulator. Can you check in "Settings > System > About" that the version of Android is really "15" ?

Note that 1.30.0 doesn't behave correctly, the system navigation and dismiss button overlap with the keyboard.

**Comment by user889252627** [comment]
M6450R_DE311_10.90.01.99R this is the Android baseboard version.
The overlapping doesn't really bother me since I want the keyboard aligned with the bottom of the screen anyway.

**Comment by user889252627** [comment]
By the way is there a legit way to get rid of the bar below the keyboard?

**Comment by Julow** [comment]
> M6450R_DE311_10.90.01.99R this is the Android baseboard version.

That's the version of your hardware, what I would like to know is the version of the operating system. It should be called "Android Version" and be a single number, perhaps "14" or "15".

> By the way is there a legit way to get rid of the bar below the keyboard?

I haven't found any way to hide this from the keyboard. On some devices, you can "Hide the gesture bar", which effectively hides the overlapping buttons. But that's not available on every devices.

**Comment by user889252627** [comment]
Yeah, sadly I couldn't find an option on my phone to hide it.
The android version is 15. The keyboard being offset vertically bug appeared right after I updated from 14 to 15 (a couple days before I decided to open this issue for it).

**Comment by MarGar12** [comment]
I also have came across this issue, Android 15 QPR1, this blank space also appears on landscape. The versions I have tried are from F-Droid and from Github Releases

![Image](https://github.com/user-attachments/assets/a69ef03d-1302-4c27-b687-4e470e835ec4)

**Comment by user889252627** [comment]
I think as a final thing I'll contact Motorola about the issue some time in the future and try to work something out altough I can't promise anything. Thanks for helping me with the issue!

**Comment by alantheprice** [comment]
I also experience space below the keyboard on Samsung with Android 15. 

![Image](https://github.com/user-attachments/assets/3070759e-3774-4cc0-abce-438f2a6d8b2b)

**Comment by Julow** [comment]
This should be fixed in https://github.com/Julow/Unexpected-Keyboard/pull/1022. Can you try the debug build at the end of this page to check if it works ? https://github.com/Julow/Unexpected-Keyboard/actions/runs/15956006762

**Comment by user889252627** [comment]
Hi! I gave the debug apk a try but sadly it didn't fix the issue.
![Screenshot_20250630-010436.Moto App Launcher.png](https://github.com/user-attachments/assets/74ffcb35-639a-43c1-9a73-8b007671ed1f)

**Comment by Julow** [comment]
@user889252627 Could this by chance be fixed by https://github.com/Julow/Unexpected-Keyboard/pull/1024 ?
The very last debug build is at the end of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/16010520885

**Comment by user889252627** [comment]
Yeah that does sound like what the culprit would be. Also this debug build fixes the issue with the keyboard hight however the smaller gap that'd normall be under the keyboard is now transparent.![Screenshot_20250702-091307.Moto App Launcher.png](https://github.com/user-attachments/assets/568c01dd-e99f-4abe-83f3-fdf97b9da787)

**Comment by Julow** [comment]
Thanks a lot for testing! I can't reproduce the bug on my device so I tried to fix it without testing. Can you try [this debug build](https://github.com/Julow/Unexpected-Keyboard/actions/runs/16035538166) ? (the [code is here](https://github.com/Julow/Unexpected-Keyboard/tree/set-windowDrawsSystemBarBackgrounds))

**Comment by user889252627** [comment]
I'm happy to help!
In this build the space is still seethru. I have't tested it in the last build but I can't click thru it.![Screenshot_20250702-234021.Moto App Launcher.png](https://github.com/user-attachments/assets/d67dbe3c-0770-4cc5-a08d-86568e95ceae)

**Comment by Julow** [comment]
Thanks :) I tried with emulators and I really can't reproduce the bug. What is your phone model ?
I tried one last thing, can you try it ? The debug build is at the bottom of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/16036662748

**Comment by user889252627** [comment]
Sadly it's still transparent. The phone is the Motorolla edge 50 fusion.

**Comment by baltitenger** [comment]
Hey, I'm also experiencing this issue since upgrading my Motorola Edge 50 Neo to Android 15. Anything else we can do to help debug this?

**Comment by fenyvessy** [comment]
Unfortunately, I’m experiencing the same issue with the large blank space under the keyboard — no matter what I try, I can’t remove it or disable it. I tested this on a Xiaomi Poco F6 and an F7 Ultra, and both behave exactly the same way.

Where it works correctly:
Android 15 AQ3A.240912.001 / Xiaomi HyperOS 2.0.205.0.VNPEUXM

Where it doesn’t work:
Android 16 BP2A.250605.031.A3 / Xiaomi HyperOS 3.0.3.0.WOMEUXM

Unexpected Keyboard version: 1.32.1

Can I help with debugging in any way? I still have the F6 where it works fine, and the F7 also worked until it was updated to the new Android version. I can run anything on both devices if that helps get closer to a solution.


![Image](https://github.com/user-attachments/assets/2e3e6c94-e499-4da0-8405-8b7ae9b0e15a)
![Image](https://github.com/user-attachments/assets/f0b7a99b-cbd7-4b9c-8a7c-8ca6d83d9fb7)
![Image](https://github.com/user-attachments/assets/c6f25bed-975a-422d-89b8-2843d6b78e8f)
![Image](https://github.com/user-attachments/assets/d391cbe1-f23f-42f9-a760-d75a6afcd874)

**Comment by Julow** [comment]
Do you still experience this with the latest version ? It's been available on Google Play for a while and will be on F-Droid soon.

**Comment by user889252627** [comment]
No it seems fixed now. I can't tell you exactly when it was fixed tho. I've been using the debug version you sent me since.
Thanks for fixing the bug!

**Comment by Julow** [comment]
Thanks for confirming :) Closing.
