### ISSUE TITLE
Empty bottom margin on Samsung A 56

### ISSUE THREAD

**Issue by trebor-salim** [Julow/Unexpected-Keyboard#946]
Empty bottom margin on Samsung A 56 and keyboard shifted sideways in landscape orientation.

![Image](https://github.com/user-attachments/assets/6082df89-c6ed-4424-8822-5dc069b7d652)

![Image](https://github.com/user-attachments/assets/da8bfd31-f15b-4f30-b441-058bcbee9ebb)

**Comment by fpczk** [comment]
I have the same problem on my Samsung Galaxy S25.

> I've made a shot in the dark in [this branch](https://github.com/Julow/Unexpected-Keyboard/tree/edge-to-edge-fits-nav-bar), can you try the debug build at the end of [this page](https://github.com/Julow/Unexpected-Keyboard/actions/runs/14012758991) ?

This works for me, the spacing in the debug build is correct.

**Comment by OpticTeadrop** [comment]
I have a similiar problem (poco x5 pro), but unfortunately the debug build doesn't fix for me - the bottom margin is still there

**Comment by trebor-salim** [comment]
@Julow Sorry, I didn't have time to check earlier. I check it now and this patch works on my phone, the problem is gone. Thanks a lot :)

**Comment by Frodotus** [comment]
Having the same problem after version 1.29.1. Debug build fixes the problem with my Galaxy S25U also. Thanks!

**Comment by trebor-salim** [comment]
When is this patch scheduled for release?

**Comment by Spike-from-NH** [comment]
Version 1.31.1 was done on 29-Mar. Going by the date of your post, this change should be in it.

**Comment by Spike-from-NH** [comment]
@alotbsol555, ah! in that case, my answer is wrong and @Julow would have to say when he would add it.

**Comment by h0tk3y** [comment]
This issue also started to manifest for me on Samsung Galaxy S24 Ultra once I updated to Android 15.

**Comment by h0tk3y** [comment]
UPD to the above: on Samsung, this seems to be connected with the nav bar. When I changed the nav bar to buttons, the extra margin disappeared with the debug build, but it is still there with the release.

![Image](https://github.com/user-attachments/assets/61be6d0d-d33d-4da9-a0bc-372e2fde97d9)
![Image](https://github.com/user-attachments/assets/425674fa-2bde-4b0c-b69a-0a433d3ec5f8)

**Comment by slartibart70** [comment]
same is true for xiaomi 13T, since the android 15 update i have this huge offset from the bottom of the screen.
This is still a problem with v.1.31.1

And yes, this is definitely the area where 'button mode' operation of the android-ui defines the space for drawing buttons.
I use gesture-navigation, so the bottom area is empty but unexp.keyboard is still shifted up 
This is very annoying

**Comment by trebor-salim** [comment]
Is this a big issue that is difficult to release? I feel like it's already solved, but I don't know why it's not being released...
It is difficult to use the keyboard comfortably with such a bottom margin.
Please consider releasing a version with this fix 🙏

**Comment by zmv7** [comment]
Latest version 1.31.1. Can reproduce on all of my Android 15 devices: S24U, Redmi K20 Pro (Crdroid), Mi Pad 6 Pro. The biggest margin is on S24U.
Don't have extra time to compile upstream myself for now unfortunately

**Comment by jggamba** [comment]
Samsung Galaxy S22 same issue; the "edge-to-edge-fits-nav-bar" debug buid did not solved the gap

**Comment by aaronrolls** [comment]
I also have this issue on my S23 with One UI 7. I have it with both gestures and navigstion buttons in thr latest build

**Comment by treytorrez** [comment]
same issue here, relatively new samsung device with one UI 7
![Screenshot_20250518_125237_GitHub.jpg](https://github.com/user-attachments/assets/290c98e8-4783-44a0-bb0d-4249d2962a4c)

**Comment by parkerlreed** [comment]
Strange, Wonder why the debug works for some and not others.

**Comment by aaronrolls** [comment]
> Strange, Wonder why the debug works for some and not others.

The debug build works for me too. Margins are working on the debug build correctly but not on the release. I thought at first that it was giving me extra space because it thought I had gesture nav bar activated when I didn't. But I really don't know.

**Comment by pschiit** [comment]
Actually no the debug doesn't solve the margin. I have the margin at 0 but it looks like this![Screenshot_20250519_092211_GitHub.jpg](https://github.com/user-attachments/assets/985ac3e4-60d9-4c43-85b7-8189474fd4de)

Also, after sometime in termux and rotating my phone, the margin grew back to the same size as the non debug version I had to restart my phone to make it smaller.

**Comment by harryaskham** [comment]
One more fixed via the deubg build:
- S24 Ultra, broke upgrading to OneUI 7
- Gesture navigation
- Previously updated to a different debug build to fix the same issue, but looks like since then I'd reverted back to the Play Store version

**Comment by jacobot1** [comment]
I have the same issue with S22 Ultra running Android 15 and One UI 7 with nav buttons instead of gestures. I tried the debug build but the problem persists.

**Comment by jacobot1** [comment]
> For me helps to install **https://github.com/Julow/Unexpected-Keyboard/tree/edge-to-edge-fits-nav-bar** but 1.29.1 version. **S21+ oneui7**

That branch doesn't seem to have its own releases section; I suppose I would need to build it from source?

**Comment by kindrowboat** [comment]
This issue affected [me] as well. The debug version fixed the problem for [me]. [I'd] love to see this get merged in and released!

System information:

- Product name: Galaxy Z Fold5
- Model name: SM-F946W
- One UI version: 7.0
- Android version: 15

**Comment by handycz** [comment]
On my s22, the gap is also present after the update. The debug build makes it a bit smaller but it's still there.

**Comment by zachpoblete** [comment]
The debug builds work for the Samsung Galaxy A35!

**Comment by tutacat** [comment]
Issue experienced on stable on Galaxy S24 Android 15

The height always matches the navigation bar. ~~Is this possibly~~ was caused by trying to draw under the navigation bar? Or from rounded device corners? Maybe the two are having interplay, or with some other system.

In landscape there is also extra padding added on the left side only. This feels like it's probably not related to system notch hiding as it extends further than that, and doesn't change sides when rotated.

**Comment by ToffoCZ** [comment]
ONe UI 7 - Some buttons/gestures settings of navibar has been removed/hiddened (at least on my S21+) so try to use Good lock labs app https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.android.goodlock with their addon navistar https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.systemui.navillera (Good Lock Labs is in cooperation with Samsung if you are scared). There you should get back some setting of navbar and others. I have tried it and margin got a little bit smaller before I found 1.29.1...

**Comment by Axillman** [comment]
The debug version did not work for me, I tried everything and nothing seemed to be working until I turned of these 2 settings and the margin disappeared.

![Screenshot_20250628_160120_Settings.jpg](https://github.com/user-attachments/assets/a4276b3d-1f23-43f0-90d6-41f77f9c0c61)

**Comment by Julow** [comment]
Thanks to everyone commenting on this issue. I merged the fix in https://github.com/Julow/Unexpected-Keyboard/pull/1022

**Comment by tutacat** [comment]
> ONe UI 7 - Some buttons/gestures settings of navibar has been removed/hiddened (at least on my S21+) so try to use Good lock labs app https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.android.goodlock with their addon navistar https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.systemui.navillera (Good Lock Labs is in cooperation with Samsung if you are scared). There you should get back some setting of navbar and others. I have tried it and margin got a little bit smaller before I found 1.29.1...

Navigation bar is added while keyboard is open to add a back button.
You are right, it exactly matches the navigation bar when the navigation bar size changes. This further adds to my suspicion there is a miscalculation when trying to draw edge-to-edge underneath system UI elements.

**Comment by parkerlreed** [comment]
> The debug version did not work for me, I tried everything and nothing seemed to be working until I turned of these 2 settings and the margin disappeared.
> 
> ![Screenshot_20250628_160120_Settings.jpg](https://github.com/user-attachments/assets/a4276b3d-1f23-43f0-90d6-41f77f9c0c61)

Both of these are off, using the latest actions apk from the PR above, still have a huge margin with everything set to 0 on Margin Bottom.

Samsung Flip 6 on Android 15

![Screenshot_20250701_080433_Unexpected Keyboard (Debug).jpg](https://github.com/user-attachments/assets/9d0f5999-fd2d-44f1-aeec-8f2728dcb130)

**Comment by parkerlreed** [comment]
Okay it's finally working with the very very latest actions https://github.com/Julow/Unexpected-Keyboard/actions/runs/15958106808

![Screenshot_20250701_080833_GitHub.jpg](https://github.com/user-attachments/assets/d745953b-fa13-4b6e-bbc1-fa41f28a44f5)

**Comment by Julow** [comment]
Thanks a lot for testing this!
